# Generated by Django 5.1.3 on 2024-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='member',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='%(class)s_of_the_club', to='members.member', verbose_name='Club members'),
        ),
    ]
